---
name: 'Release Ruby gems'
description: "Release Ruby gems with minimal tooling"
inputs:
  repository:
    description: 'Repository to checkout'
    required: false
    type: string
  ref:
    description: 'Git ref to checkout'
    required: false
    type: string
  ruby_version:
    description: 'Ruby version used to build'
    default: 'ruby'
    type: 'string'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: 'Install Ruby ${{ inputs.ruby_version }}'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '${{ inputs.ruby_version }}'
    - name: Build gem
      shell: bash
      run: gem build *.gemspec
    - uses: rubygems/configure-rubygems-credentials@v1.0.0
    - name: Publish gem to rubygems.org
      shell: bash
      run: gem push *.gem
    - name: Wait for release to propagate
      shell: bash
      run: |
        gem install rubygems-await
        gem await *.gem
